# Generated by Django 3.2.6 on 2021-10-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=1)),
                ('weight', models.CharField(blank=True, default=1, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, default='')),
                ('client', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=200)),
                ('thing', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('password1', models.CharField(default='', max_length=255)),
                ('password2', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_spend', models.IntegerField(default=0)),
                ('bills', models.TextField(default='Zadny_default')),
                ('person', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.IntegerField(default=0)),
                ('item_amount', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=255)),
                ('cart', models.TextField(default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(default='Parents', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
