# Generated by Django 3.2.6 on 2021-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoney',
            name='date',
            field=models.CharField(default='01.01.2000', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.CharField(default='01.01.2000', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bills',
            field=models.TextField(default=''),
        ),
    ]
