# Generated by Django 3.2.6 on 2021-10-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_buyitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='cart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cart'),
        ),
    ]
