# Generated by Django 3.2.6 on 2021-10-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_buyitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password2',
        ),
    ]
