# Generated by Django 3.2.6 on 2021-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='compare_date',
            field=models.IntegerField(null=True),
        ),
    ]
